#!/bin/bash
#
# Setup directory structure and files to the destination path.
#

if [ "$1" == "" ] ; then
  echo $ $0 [DESTINATION_PATH]
  exit -1
fi

SRC_DIR=..
DST_DIR=$1
CREATED_DATE=`date +"%Y-%m-%d"`

if ! [ -d $DST_DIR ] ; then
  echo "Cannot find directory $DST_DIR"
  exit -1
fi

mkdir -p $DST_DIR/Documentation/references
mkdir -p $DST_DIR/Documentation/res/images
mkdir -p $DST_DIR/Journal
mkdir -p $DST_DIR/blog
mkdir -p $DST_DIR/dev
mkdir -p $DST_DIR/dev/apple
mkdir -p $DST_DIR/dev/android
mkdir -p $DST_DIR/dev/artwork
mkdir -p $DST_DIR/script

# Copying documentation files.
cp -Rvn $SRC_DIR/Documentation/* $DST_DIR/Documentation

# Create initial template for Journal files.
if ! [ -f $DST_DIR/Journal/YYYY-MM-DD-Title.md ] ; then
  echo "# YYYY-MM-DD TITLE" >> $DST_DIR/Journal/YYYY-MM-DD-Title.md
  echo "$CREATED_DATE Project Created" >> $DST_DIR/Journal/$CREATED_DATE-ProjectCreated.md
  echo "Project created from PrimeCoder's Project Template." >> $DST_DIR/Journal/$CREATED_DATE-ProjectCreated.md
  echo "For more information, visit https://primecoder.github.io/ProjectTemplate/" >> $DST_DIR/Journal/$CREATED_DATE-ProjectCreated.md
fi

# Create initial template for blog files.
if ! [ -f $DST_DIR/blog/YYYY-MM-DD-Title.md ] ; then
  echo "# YYYY-MM-DD TITLE" >> $DST_DIR/blog/YYYY-MM-DD-Title.md
fi

# Copy initial Xcode workspace and project.
cp -Rvn $SRC_DIR/dev/apple/* $DST_DIR/dev/apple

echo 
echo "Done"
echo "Destination project now contains:"
find $DST_DIR -type d
